import type { SledDef } from '../types/sled'

export const SLEDS: SledDef[] = [
  {
    id: 'starter',
    name: 'The Rookie',
    price: 0,
    speed: 3,
    accel: 3,
    handling: 5,
    braking: 3,
    variant: 'basic',
    color: '#4488cc',
    accentColor: '#88bbee',
  },
  {
    id: 'swift',
    name: 'Swift Runner',
    price: 100,
    speed: 5,
    accel: 4,
    handling: 5,
    braking: 4,
    variant: 'sport',
    color: '#cc4444',
    accentColor: '#ee8888',
  },
  {
    id: 'thunderbolt',
    name: 'Thunderbolt',
    price: 250,
    speed: 7,
    accel: 5,
    handling: 6,
    braking: 5,
    variant: 'sport',
    color: '#ccaa22',
    accentColor: '#eecc44',
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    price: 500,
    speed: 8,
    accel: 7,
    handling: 7,
    braking: 6,
    variant: 'pro',
    color: '#22cc66',
    accentColor: '#66ee99',
  },
  {
    id: 'glacier',
    name: 'Glacier Elite',
    price: 800,
    speed: 9,
    accel: 8,
    handling: 8,
    braking: 8,
    variant: 'elite',
    color: '#8844cc',
    accentColor: '#bb88ee',
  },
  {
    id: 'legend',
    name: 'The Legend',
    price: 1500,
    speed: 10,
    accel: 9,
    handling: 10,
    braking: 9,
    variant: 'legendary',
    color: '#cc8800',
    accentColor: '#ffbb33',
  },
]

export function getSled(id: string): SledDef {
  return SLEDS.find((s) => s.id === id) ?? SLEDS[0]
}
